_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.22
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.22
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 128
dropout_rate:
    value: 0
model:
    value: vit_b_16
num_epochs:
    value: 200
pretrained:
    value: true
test_set_ratio:
    value: 0.19999999999999996
train_set_ratio:
    value: 0.8
